import AsyncStorage from "@react-native-async-storage/async-storage";
import { createAsyncThunk, createSlice, PayloadAction } from "@reduxjs/toolkit";

import { login, logout } from "../services/authService";
import { LoginBody } from "../types/auth";
import { User } from "../types/user";
// import { removeItem, setItem } from "../utils/localStorage";
import { RootState } from "../utils/store";

export interface AuthState {
  user: User | null;
  isLoading: boolean;
  isLoggedIn: boolean | null;
  errors: {
    loginError: string;
  };
  // tokens: Tokens | null;
}

const initialState: AuthState = {
  user: null,
  isLoading: true,
  isLoggedIn: null,
  errors: {
    loginError: "",
  },
  // tokens: null
};

// TODO handle unauth login
export const loginAction = createAsyncThunk(
  "auth/loginAction",
  async (body: LoginBody, thunkAPI) => {
    const user = await login(body);

    AsyncStorage.setItem("user", JSON.stringify(user));

    return user;
  },
);

export const logoutAction = createAsyncThunk(
  "auth/logout",
  async (_, thunkAPI) => {
    await logout();
    AsyncStorage.removeItem("user");

    return true;
  },
);

export const authSlice = createSlice({
  name: "auth",
  initialState,
  // The `reducers` field lets us define reducers and generate associated actions
  reducers: {
    setUser: (state, action: PayloadAction<User>) => {
      state.user = action.payload;
      state.isLoading = false;
    },
    setIsLoggedIn: (state, action: PayloadAction<boolean>) => {
      state.isLoggedIn = action.payload;
    },
    resetLoginError: (state) => {
      state.errors.loginError = "";
    },
    resetState: () => initialState,
  },
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {
    builder
      .addCase(loginAction.fulfilled, (state, action) => {
        const user = action.payload;
        state.user = user;
      })
      .addCase(loginAction.rejected, (state, action) => {
        const error = action.error;
        console.log("Login error: ", error);

        const { message } = error;

        state.errors.loginError = message ?? "Unknown error";
      })
      .addCase(logoutAction.fulfilled, (state, action) => {
        state.user = null;
      });
  },
});

/**
 * Action exports
 */
export const { setUser, resetLoginError, resetState, setIsLoggedIn } =
  authSlice.actions;

/**
 * Selectors
 */
export const selectUser = (state: RootState) => state.auth.user;
export const selectIsLoading = (state: RootState) => state.auth.isLoading;
export const selectIsLoggedIn = (state: RootState) => state.auth.isLoggedIn;
export const selectLoginError = (state: RootState) =>
  state.auth.errors.loginError;
// export const selectTokens = (state: RootState) => state.auth.tokens;

/**
 * Reducer export
 */
export default authSlice.reducer;
